name: Build (Release)

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - uses: extractions/setup-just@v4

      - name: Install NSIS
        uses: negrutiu/nsis-install@v2

      - name: Set short SHA
        shell: pwsh
        run: |
          "SHORT_SHA=$("${{ github.sha }}".Substring(0, 7))" >> $env:GITHUB_ENV

      - name: Build and package
        run: just ci-publish-windows

      - uses: actions/upload-artifact@v7
        with:
          name: froststrap-release-win-x64-${{ env.SHORT_SHA }}
          path: build/*

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - name: Build, sign (if release), and package
        env:
          SIGN: true
          CERT_P12_BASE64: ${{ secrets.CERT_P12_BASE64 }}
          CERT_P12_INSTALLER_BASE64: ${{ secrets.CERT_P12_INSTALLER_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          DEVELOPER_ID_APP: ${{ secrets.DEVELOPER_ID_APP }}
          DEVELOPER_ID_INSTALLER: ${{ secrets.DEVELOPER_ID_INSTALLER }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APP_STORE_CONNECT_P8_CONTENT: ${{ secrets.APP_STORE_P8_CONTENT }}
        run: |
          chmod +x Scripts/package/publish-macos.sh
          ./Scripts/package/publish-macos.sh

      - uses: actions/upload-artifact@v7
        with:
          name: froststrap-release-macos-universal-${{ env.SHORT_SHA }}
          path: build/Froststrap.pkg

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - uses: extractions/setup-just@v4

      - uses: DeterminateSystems/nix-installer-action@v22

      - uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Build and package binaries
        run: just ci-publish-linux

      - name: Install Flatpak builder dependencies
        run: |
          sudo apt-get install -y flatpak flatpak-builder

      - name: Build Flatpak package from binary
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: Scripts/flatpak/xyz.froststrap.yml
          cache-key: flatpak-builder-${{ hashFiles('flatpak/xyz.froststrap.yml', '**/*.csproj', '**/packages.lock.json') }}
          bundle: build/Froststrap-linux-x64.flatpak

      - uses: actions/upload-artifact@v7
        with:
          name: froststrap-release-linux-x64-${{ env.SHORT_SHA }}
          path: build/*

  release:
    needs:
      - build-windows
      - build-linux
      - build-macos

    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Download Windows artifact
        uses: actions/download-artifact@v7
        with:
          name: froststrap-release-win-x64-${{ env.SHORT_SHA }}
          path: release

      - name: Download macOS artifact
        uses: actions/download-artifact@v7
        with:
          name: froststrap-release-macos-universal-${{ env.SHORT_SHA }}
          path: release

      - name: Download Linux artifact
        uses: actions/download-artifact@v7
        with:
          name: froststrap-release-linux-x64-${{ env.SHORT_SHA }}
          path: release

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Froststrap ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-') }}
          draft: true
          fail_on_unmatched_files: true
          files: |
            release/Froststrap-Setup.exe
            release/Froststrap.pkg
            release/Froststrap-linux-x64.AppImage
            release/Froststrap-linux-x64.deb
            release/Froststrap-linux-x64.rpm
            release/Froststrap-linux-x64.flatpak