name: CI (Release)
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Install NSIS
        uses: negrutiu/nsis-install@v2

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Build and package
        run: just publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Froststrap(Release) (${{ github.sha }})
          path: .\build\*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Froststrap(Release) (${{ github.sha }})
          path: release

      - name: Rename binaries
        run: mv release/Froststrap.exe Froststrap-${{ github.ref_name }}.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, '-') }}
          draft: true
          files: Froststrap-${{ github.ref_name }}.exe
          name: Froststrap ${{ github.ref_name }}
          fail_on_unmatched_files: true
