name: Publish to Winget

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Froststrap.Froststrap
          token: ${{ secrets.WINGET_TOKEN }}
