name: Publish to Winget

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@a8fff44b123f115ce4c21543edf8b677376fc7e0
        with:
          identifier: Froststrap.Froststrap
          installers-regex: '\.msi$'
          token: ${{ secrets.WINGET_TOKEN }}
